### PR TITLE
GT-1842 Create a UserActivity model that calculates user activity numbers

### PR DESCRIPTION
**Pull request by frett**
This is a model that will calculate the user activity counters for the new account UI.

Badges will be coming in a separate PR.

How this should work in iOS is whenever you need to log a user counter, there is a `UserCounterNames` object that you can get the appropriate counter name from.
```swift
UserCounterNames.shared.TOOL_OPEN(tool: toolAbbrev)
```

Then when you want to get the calculated stats, you would create a new `UserActivity` object with the current counters as a dictionary.

```swift
let activity = UserActivity(counters: countersDict)
activity.toolOpens
activity.lessonCompletions
```

### CODE REVIEW

**Comment by levieggertcru** [comment]
Hey @frett , do I have this understanding correct?

If I wanted to calculate tool opens combined for all of the tools, I would use ```UserCounterNames.shared.TOOL_OPEN``` on each tool to generate a ```String``` that is used as the hash in the ```counters: Map<String, Int>```.  Then each ```Int``` value in ```counters: Map<String, Int>``` would come from the mobile content api?

I would then take my generated ```counters: Map<String, Int>``` to create a UserActivity and ```.toolOpens``` would give me a total of all tool opens from the generated ```counters: Map<String, Int>```?

**Comment by frett** [comment]
@levieggertcru yes, there is an authenticated user API for incrementing counters. one of the things it takes is the counter "name", which is what `UserCounterNames` provides consistently across Android & iOS.

There is another API that retrieves the current counts from the API, which can be massaged into the appropriate "name -> count" dictionary to pass to this method.

Right now this doesn't look like too much (just aggregating counters into properties), but the next PR will expose which "Badges" the user has earned.

**Comment by levieggertcru** [comment]
Okay thanks that makes sense and good to know about using the names against the api as well when updating those counters.

**Review by levieggertcru — APPROVED** [review]

**Comment by frett** [comment]
@levieggertcru This is also designed so you can increment counters offline and just sync them up to the API the next time you have internet access. The local counters can be used to drive the UserActivity objects

**Pull request merged**
